# Generated by Django 5.2.13 on 2026-04-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=200, verbose_name='Last Name')),
                ('phoneNum', models.CharField(max_length=200, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
