# Generated by Django 6.0.4 on 2026-06-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstName',
            field=models.CharField(blank=True, max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=200, verbose_name='Phone Number'),
        ),
    ]
