# Generated by Django 6.0.4 on 2026-04-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_u', models.PositiveSmallIntegerField(choices=[(6, '6U'), (9, '9U'), (12, '12U'), (15, '15U'), (18, '18U'), (21, '21U')])),
                ('width_mm', models.PositiveIntegerField(choices=[(600, '600mm'), (800, '800mm')])),
                ('depth_mm', models.PositiveIntegerField(choices=[(600, '600mm'), (800, '800mm')])),
                ('color', models.CharField(choices=[('RAL7035', 'Light Gray (RAL 7035)'), ('custom', 'Custom on Request')], default='RAL7035', max_length=20)),
                ('sku', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
            ],
        ),
    ]
