# Generated by Django 6.0.4 on 2026-04-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
    ]
