# Generated by Django 6.0.4 on 2026-04-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_optional_alter_image_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AddField(
            model_name='product',
            name='brief_discerption',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.TextField(default=''),
        ),
    ]
