# Generated by Django 6.0.4 on 2026-04-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brief_discerption',
        ),
        migrations.AlterField(
            model_name='product',
            name='optional',
            field=models.TextField(default='', null=True),
        ),
    ]
