# Generated by Django 6.0.4 on 2026-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_brief_discerption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='optional',
            field=models.TextField(),
        ),
    ]
