# Generated by Django 6.0.4 on 2026-04-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='optional',
            field=models.TextField(blank=True, default=''),
        ),
    ]
