# Generated by Django 6.0.4 on 2026-05-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_optional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='height_u',
            new_name='height_mm',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='data_sheet',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='depth_rail_mm',
            field=models.PositiveIntegerField(choices=[(600, '600mm'), (800, '800mm')], null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='static_load_kg',
            field=models.PositiveIntegerField(choices=[(600, '600mm'), (800, '800mm')], null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
