# Generated by Django 6.0.4 on 2026-05-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rename_height_u_productvariant_height_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='depth_mm',
            field=models.PositiveIntegerField(choices=[(300, '300mm'), (400, '400mm'), (500, '500mm'), (600, '600mm'), (700, '700mm'), (800, '800mm'), (900, '900mm'), (1000, '1000mm')]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='depth_rail_mm',
            field=models.PositiveIntegerField(choices=[(300, '300mm'), (400, '400mm'), (500, '500mm'), (600, '600mm'), (700, '700mm'), (800, '800mm'), (900, '900mm'), (1000, '1000mm')], null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='height_mm',
            field=models.PositiveSmallIntegerField(choices=[(18, '18U'), (21, '21U'), (24, '24U'), (26, '26U'), (32, '32U')]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='static_load_kg',
            field=models.PositiveIntegerField(choices=[(300, '300mm'), (400, '400mm'), (500, '500mm'), (600, '600mm'), (700, '700mm'), (800, '800mm'), (900, '900mm'), (1000, '1000mm')], null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='width_mm',
            field=models.PositiveIntegerField(choices=[(300, '300mm'), (400, '400mm'), (500, '500mm'), (600, '600mm'), (700, '700mm'), (800, '800mm'), (900, '900mm'), (1000, '1000mm')]),
        ),
    ]
