# Generated by Django 6.0.4 on 2026-05-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productvariant_depth_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='height_U',
            field=models.PositiveSmallIntegerField(choices=[(6, '6U'), (9, '9U'), (12, '12U'), (15, '15U'), (18, '18U'), (21, '21U'), (24, '24U'), (26, '26U'), (32, '32U'), (36, '36U'), (42, '42U'), (45, '45U'), (47, '47U')], null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(choices=[('RAL 9005', 'BLACK (RAL 9005)'), ('RAL7035', 'Light Gray (RAL 7035)')], default='RAL7035', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='depth_mm',
            field=models.PositiveIntegerField(choices=[(100, '100mm'), (250, '250mm'), (300, '300mm'), (450, '450mm'), (510, '510mm'), (600, '600mm'), (700, '700mm'), (800, '800mm'), (1000, '1000mm'), (1200, '1200mm')]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='depth_rail_mm',
            field=models.PositiveIntegerField(choices=[(350, '350mm'), (500, '500mm'), (600, '600mm'), (650, '650mm'), (700, '700mm'), (800, '800mm'), (850, '850mm'), (900, '900mm'), (1000, '1000mm'), (1050, '1050mm'), (1100, '1100mm')], null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='height_mm',
            field=models.PositiveSmallIntegerField(choices=[(365, '365mm'), (495, '495mm'), (630, '630mm'), (760, '760mm'), (895, '895mm'), (985, '985mm'), (1100, '1100mm'), (1200, '1200mm'), (1500, '1500mm'), (1720, '1720mm'), (2020, '2020mm'), (2160, '2160mm'), (2250, '2250mm')]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='static_load_kg',
            field=models.PositiveIntegerField(choices=[(40, '40kg'), (400, '400kg'), (500, '500kg'), (600, '600kg'), (800, '800kg'), (1100, '1100kg')], null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='width_mm',
            field=models.PositiveIntegerField(choices=[(100, '100mm'), (250, '250mm'), (300, '300mm'), (450, '450mm'), (510, '510mm'), (600, '600mm'), (700, '700mm'), (800, '800mm'), (1000, '1000mm'), (1200, '1200mm')]),
        ),
    ]
