# Generated by Django 6.0.4 on 2026-05-20 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_productvariant_height_u_alter_productvariant_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_fans', models.PositiveIntegerField(blank=True, null=True)),
                ('material_type', models.CharField(blank=True, choices=[('galvanised', 'Galvanised'), ('steel', 'Steel'), ('aluminum', 'Aluminum'), ('stainless', 'Stainless Steel')], max_length=20)),
                ('door_type', models.CharField(blank=True, choices=[('glass', 'Glass'), ('metal', 'Metal'), ('perforated', 'Perforated')], max_length=20)),
                ('accessories', models.TextField(blank=True)),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='quotations/')),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
