# Generated by Django 6.0.4 on 2026-06-07 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_quotation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalogue',
            field=models.FileField(blank=True, null=True, upload_to='catalogue/'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='products_list',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('quoted', 'Quoted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(blank=True, max_length=20)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('depth', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('material', models.CharField(blank=True, choices=[('galvanised', 'Galvanised'), ('steel', 'Steel'), ('aluminum', 'Aluminum'), ('stainless', 'Stainless Steel')], max_length=20)),
                ('door', models.CharField(blank=True, choices=[('glass', 'Glass'), ('metal', 'Metal'), ('perforated', 'Perforated')], max_length=20)),
                ('accessories', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.quotation')),
            ],
        ),
    ]
