# Generated by Django 6.0.4 on 2026-06-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_catalogue_quotation_products_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='door_type',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='number_of_fans',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='products_list',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='reference_file',
        ),
    ]
